### ISSUE TITLE
No Module EasyAi

### ISSUE THREAD

**Issue by Thatoddone1** [GustyCube/EasilyAI#7]
I am experiencing an error with using the Ollama service. Traceback:

```
Traceback (most recent call last):
  File "/easilyai_practice.py", line 1, in <module>
    import easilyai
  File "/venv/lib/python3.13/site-packages/easilyai/__init__.py", line 1, in <module>
    from easilyai.app import create_app, create_tts_app
  File "/venv/lib/python3.13/site-packages/easilyai/app.py", line 1, in <module>
    from easilyai.services.openai_service import OpenAIService
  File "/venv/lib/python3.13/site-packages/easilyai/services/openai_service.py", line 2, in <module>
    from easyai.exceptions import (
    ...<2 lines>...
    )
ModuleNotFoundError: No module named 'easyai'
```

I think this error is coming from the import statement in the `ollama_service.py` and maybe also the `openai_service.py`

it tries to import `easyai` when i think it means `easilyai`:
```
from easyai.exceptions import (
```

I will try and fix it, but if anyone has anything to add, please say! Thanks! 👍

**Comment by GustyCube** [comment]
Ah. Yes. It was originally called EasyAI but we changed it to EasilyAI. If you could please change that and any other references, that would be great!
